#home:
#  path: /
#  defaults: { _controller: 'AppBundle\Controller\DefaultController::indexAction' }
#  methods:  GET
#

setupcheck:
  path: /api/setup-check
  controller: App\Controller\DefaultController::setupCheck

api_rates_index:
  path: /api/rates
  controller: App\Controller\Api\RateController::listRates
  methods: [GET]

api_rates_history:
  path: /api/rates/{code}/history
  controller: App\Controller\Api\RateController::history
  requirements:
    code: '[A-Za-z]{3}'
  methods: [GET]

index:
  path: /{wildcard}
  defaults: { _controller: App\Controller\DefaultController::index }
  requirements:
    wildcard: .*
